### ISSUE TITLE
reactive/model-driven forms

### ISSUE THREAD

**Issue by GoNode5** [castrolol/ng2-mask-money#10]
Is this directive working with reactive/model-driven forms ?

**Comment by rodolfocop** [comment]
Hi, I had not tested with reactive/model-driven yet.
I will check and inform you as soon as possible.

**Comment by rodolfocop** [comment]
Updated package, you can use it!

**Comment by samuellessa** [comment]
**Tks!! I was looking for this since March**
I have built something of my own, but not as great as yours!!!!!
TY!!!!!!
