### ISSUE TITLE
moneyModel does not pass the value to any variable

### ISSUE THREAD

**Issue by markpenaranda** [castrolol/ng2-mask-money#11]
Given:

  <input name="moneyText" [(ngModel)]="moneyText" [(moneyModel)]="moneyValue" [money-mask-options]="{ prefix: '¥' }" mask-money />
                        

it seems that moneyModel is not binded in moneyValue. but when i console.log("moneyText") it returns the expected value. I'm not sure what's causing the issue. The directive runs as expected, only the issue regarding the moneyModel.

**Comment by sandrodemarco** [comment]
Hi.
I've the same problem...

**Comment by gleysonsampaio** [comment]
I think that your moneyModel restarts the ngModel for "zero".

**Comment by didi3r** [comment]
I solved it changing two things. First in **money-mask.directive.ts** line 11:

From
`@Output('moneyModel')`

To
`@Output('moneyModelChange')`

After this moneyModel gets binded but it will enter in an infinite loop. To fix this I changed the clear() function on **money-mask.provider.ts** line 38:

From

`
clear(textValue) {

    let value = (textValue || '0');
    let isNegative = value.indexOf('-') !== -1;
    let decimalPart ='';


    value
      .split(/\D/)
      .reverse()
      .forEach(function (element) {
        if (element) {
          decimalPart = element;
          return false;
        }
      });

    value = value.replace(/\D/g, '');
    value = value.replace(new RegExp(decimalPart + '$'), '.' + decimalPart);
    if (isNegative) {
      value = '-' + value;
    }
    return parseFloat(value);

  }
`

To

`
  clear(textValue) {

    let value = (textValue || '0');
    let isNegative = value.indexOf('-') !== -1;
    let decimalPart ='';

    value = Number(value.replace(/[^0-9\.]+/g,""));

    if (isNegative) {
      value = '-' + value;
    }
    return parseFloat(value);

  }

`

Hope this help.

**Comment by castrolol** [comment]
@didi3r Do you can push it ?

**Comment by rodolfocop** [comment]
Pr Accepted you can use it!
