### ISSUE TITLE
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:3002/ng2-money-mask

### ISSUE THREAD

**Issue by rlamba89** [castrolol/ng2-mask-money#12]
I have installed the module but when imported and tried npm run, getting 404 error for the module.

Any inputs?

![image](https://cloud.githubusercontent.com/assets/4330382/22107908/7944dfb2-de48-11e6-8a22-27f989ef1a98.png)

**Comment by rodolfocop** [comment]
Hi, you could be more specific about this error.
What version of angular that is using this component is not necessary to add in SystemJs.
I just run test using Angular-cli version 1.0.0-beta.25.5 and I did not get this problem.

**Comment by rodolfocop** [comment]
Hi, I made an update for a version angular 4 using CLI 1.0.

Any questions open issues
