### ISSUE TITLE
Error in Linux

### ISSUE THREAD

**Issue by leandrolimasi** [castrolol/ng2-mask-money#13]
Hi,

I get an error just by importing the agular module:

ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /node_modules/ng2-money-mask/node_modules/@angular/core/src/metadata/ng_module.d.ts

Angular 2.4.1
OS: Linux Arch 64
Do you can help?

**Comment by rodolfocop** [comment]
Hi, I made an update for a version angular 4 using CLI 1.0.

Any questions open issues.
