### ISSUE TITLE
Calling function 'makeDecorator', function calls are not supported

### ISSUE THREAD

**Issue by didi3r** [castrolol/ng2-mask-money#14]
Just followed the getting started instructions and when trying to compile it throws me this error:

`ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/user001/Sites/genius/node_modules/ng2-money-mask/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /Users/user001/Sites/genius/node_modules/ng2-money-mask/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /Users/user001/Sites/genius/node_modules/ng2-money-mask/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/user001/Sites/genius/node_modules/ng2-money-mask/node_modules/@angular/core/index.d.ts, resolving symbol MoneyMaskModule in /Users/user001/Sites/genius/node_modules/ng2-money-mask/src/mask/money-mask.module.ts, resolving symbol MoneyMaskModule in /Users/user001z/Sites/genius/node_modules/ng2-money-mask/src/mask/money-mask.module.ts
`

Tested with the following setup:

angular-cli: 1.0.0-beta.28.3
node: 6.9.4
os: darwin x64
@angular/common: 2.4.6
@angular/compiler: 2.4.6
@angular/core: 2.4.6
@angular/forms: 2.4.6
@angular/http: 2.4.6
@angular/platform-browser: 2.4.6
@angular/platform-browser-dynamic: 2.4.6
@angular/router: 3.4.6
@angular/upgrade: 2.4.6

Regards
Didier

**Comment by rodolfocop** [comment]
Hi, I made an update for a version angular 4 using CLI 1.0.

Any questions open issues
