### ISSUE TITLE
installing with ionic3

### ISSUE THREAD

**Issue by mgkimsal** [castrolol/ng2-mask-money#15]
probably because I'm on 3 now, but... this won't install.

> npm install ng2-money-mask --save
myapp@ /Users/michael/web/hedge1
└─┬ ng2-money-mask@0.2.4 
  ├── UNMET PEER DEPENDENCY @angular/common@2.0.2
  ├── @angular/compiler@2.0.2 
  ├── UNMET PEER DEPENDENCY @angular/core@2.0.2
  ├── @angular/forms@2.0.2 
  ├── @angular/http@2.0.2 
  ├── UNMET PEER DEPENDENCY @angular/platform-browser@2.0.2
  ├── @angular/platform-browser-dynamic@2.0.2 
  ├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
  └── zone.js@0.6.26 

npm WARN @angular/router@3.0.2 requires a peer of @angular/core@2.0.2 but none was installed.
npm WARN @angular/router@3.0.2 requires a peer of @angular/common@2.0.2 but none was installed.
npm WARN @angular/router@3.0.2 requires a peer of @angular/platform-browser@2.0.2 but none was installed.
npm WARN @angular/router@3.0.2 requires a peer of rxjs@5.0.0-beta.12 but none was installed.

Any pointers to get this to install?  I tried to just use the downloaded tar.gz file, but can't seem to get that working either.

Your docs say "You should use the version 2.x.x for Angular 2.x.x applications and the version 4.x.x for Angular 4.x.x applications."   I only see one "version" anywhere.  Am I missing something?  Thanks!

**Comment by rodolfocop** [comment]
Hi, I'm sorry, it was not done yet for the new version. 
Once we do that, we'll let you know.
@castrolol please update to npm.

**Comment by rodolfocop** [comment]
Hi, we have made update now.
You can use it without problems.
