### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gamferreira** [castrolol/ng2-mask-money#3]
Please fix your example, the option should be [money-mask-options] instead of [mask-money-options].

Also, there is a 'debugger' enabled in your code, not sure you want to distribute it this way.

The error I am getting is:

error_handler.js:46 EXCEPTION: value.indexOf is not a function

error_handler.js:52 TypeError: value.indexOf is not a function
    at MoneyMaskProvider.apply (http://localhost:3000/6.chunk.js:37921:49)
    at MoneyInputService.set [as value] (http://localhost:3000/6.chunk.js:37572:46)
    at MoneyInputEventHandler.setValue (http://localhost:3000/6.chunk.js:37441:33)

My tag:

  <input  id="alcada_de" name="alcada_de" class="form-control"
                                       required="required" [(ngModel)]="workflowUsuarioModel.alcada_de"
                                       [(moneyModel)]="workflowUsuarioModel.alcada_de" mask-money [money-mask-options]="{ prefix: '', thousands: '.', decimal: ',' }" placeholder="0,00">

I changed money-mask.directive.ts to:

  ngOnChanges(...changes: any[]) {
    if ("moneyModel" in changes) {
      setTimeout(() => this.inputEventHandler.setValue(changes[0].moneyModel), 100);
    }
  }

The issue seems to be fixed, however I am not sure I applied the right solution.

**Comment by castrolol** [comment]
I'll replicate and remove the debugger

**Comment by castrolol** [comment]
Fixed the issues 

The moneyModel problem, be fixed: 
[money-input.service.ts#L49](https://github.com/castrolol/ng2-mask-money/blob/master/src/mask/money-input.service.ts#L49) 


The readme be changed to correct attribute name...

@gamferreira you can update the package to  [ng2-money-mask@0.2.4](https://www.npmjs.com/package/ng2-money-mask)

**Comment by gamferreira** [comment]
Hi @castrolol , after the latest upgrade it stopped throwing the error I reported , however, when I type a value the input remains showing 0,00, that is, the input value is not changed at all

**Comment by gamferreira** [comment]
BTW , there is a console.log(...) on one of your scripts , it would be nice to remove it

**Comment by castrolol** [comment]
Thanks @gamferreira I`ll remove it
