### ISSUE TITLE
Can't bind to 'moneyModel' since it isn't a known property of 'input'.

### ISSUE THREAD

**Issue by StevenSerrien** [castrolol/ng2-mask-money#4]
Hello!

Followed the instructions, but getting an error when trying to paste following syntax in my form.
_<input [(ngModel)]="moneyText" [(moneyModel)]="moneyValue" mask-money />_

ERROR: **Can't bind to 'moneyModel' since it isn't a known property of 'input'.**

**Comment by castrolol** [comment]
Hi Steven, 

You added the `MoneyMaskDirective` to your AppModule ?

You snippet worked for me

**Comment by tuliogalli** [comment]
unfortunately my did not work, I had to hand in the on blur.

https://www.dropbox.com/s/nou8fk4avar9ik1/Captura%20de%20tela%202016-11-06%2017.56.35.png?dl=0

https://www.dropbox.com/s/4s6mlbihyo2hrnj/Captura%20de%20tela%202016-11-06%2017.56.56.png?dl=0

With this my way around the ship to model the correct value.


Are there any files that I send to help identify the problem?
Thank you and congratulations on Development. Excellent.

**Comment by cdarrigo** [comment]
@castrolol - Can you post a sample of what you're AppModule looks like.  In the docs you said to import MoneyMaskModule, but in the comment above you said to import MoneyMaskDirective.

I am having the same issue as @StevenSerrien and would like to see a working sample. 

Thanks.

**Comment by castrolol** [comment]
@cdarrigo (and @StevenSerrien ) I mistaken, it's `MoneyMaskModule` and a working code it's 



```

import {MoneyMaskModule} from 'ng2-money-mask'

@NgModule({
  imports: [ BrowserModule, MoneyMaskModule ],
  declarations: [ App ],
  bootstrap: [ App ]
})
export class AppModule {}
```

**Comment by castrolol** [comment]
@tuliogalli sorry for the delay to answer

I don't update the value on keyup, you need it ?

in this file, I attach only keypress and keydown
https://github.com/castrolol/ng2-mask-money/blob/master/src/mask/money-input-event.handler.ts

If you need, can send a PR,  in next week I'll have more time to dedicate to this fix

**Comment by rodolfocop** [comment]
Hi @StevenSerrien,this problem was occurring because the selector does not accept more html elements. This last update corrected this problem.
Please resolve this issue.

**Comment by StevenSerrien** [comment]
Thank you!
