### ISSUE TITLE
AOT Compilation?

### ISSUE THREAD

**Issue by cdarrigo** [castrolol/ng2-mask-money#7]
Have you tried to use this component with AOT compilation?

I'm getting this exception during compilation (ng build --aot):

> Unexpected value 'MoneyMaskModule' imported by the module 'SharedModule'

here's my shared module:
```
import {MoneyMaskModule} from "ng2-money-mask";
@NgModule({
  imports: [
...
    MoneyMaskModule
  ],
exports: [
    ...
MoneyMaskModule
]
export class SharedModule {}
```

**Comment by rodolfocop** [comment]
Hi @cdarrigo, What version of cli are you using?  See this [official angular thread](https://github.com/angular/angular/issues/11262) for reference. Updating to the official release of Angular 2 might help.

**Comment by rodolfocop** [comment]
Hi, I made an update for a version angular 4 using CLI 1.0 and AOT.
Any questions open issues
