### ISSUE TITLE
Erro: Unexpected value 'MoneyMaskModule' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by caiolima86** [castrolol/ng2-mask-money#8]
Hello,

I installed or script in version 2.4.1 of angular, I did the import in app.module.ts.

But I am having the error: Unexpected value 'MoneyMaskModule' imported by the module 'AppModule'.

Do you know how I can correct this problem?

Thanks for the project.

**Comment by rodolfocop** [comment]
Hi @caiolima86 , Here #9, are the changes the project to a version 2.4.1 of angular and changed the problems with implicity. 
Questions or problems please let me know.

Commit #9

**Comment by gamferreira** [comment]
Hi @rodolfocop , I updated the code per your last message on this thread and it is failing with the same error. I'm using Angular 2.4.1

**Comment by rodolfocop** [comment]
Hi, I made an update for a version angular 4 using CLI 1.0.

Any questions open issues
